{% set version = "0.7.1" %}

package:
  name: pytest-check-links
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest_check_links/pytest_check_links-{{ version }}.tar.gz
  sha256: b5c45ced56865a76d392f29892ad6af4dfba11111a87a669ca69378aeaca30eb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pytest-check-links = pytest_check_links.__main__:main

requirements:
  host:
    - pbr >=1.9
    - pip
    - python >=3.7
    - setuptools >=17.1
  run:
    - docutils
    - html5lib
    - nbconvert
    - nbformat
    - pytest >=7
    - python >=3.7
    - requests

test:
  imports:
    - pytest_check_links
  commands:
    - pip check
    - pytest-check-links --version
  requires:
    - pip

about:
  home: https://github.com/jupyterlab/pytest-check-links
  summary: Check links in files
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
