{% set version = "0.9.0" %}

package:
  name: pytest-check-links
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest_check_links/pytest_check_links-{{ version }}.tar.gz
  sha256: 1dc86f01add36649ae595a3ef562908b210c3787a25857fb97b75b9f7d03415e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - pytest-check-links = pytest_check_links.__main__:main

requirements:
  host:
    - hatchling >=1.5
    - pip
    - python >=3.8
  run:
    - docutils
    - html5lib
    - nbconvert
    - nbformat
    - pytest >=7
    - python >=3.8
    - requests

test:
  imports:
    - pytest_check_links
  commands:
    - pip check
    - pytest-check-links --version
  requires:
    - pip

about:
  home: https://github.com/jupyterlab/pytest-check-links
  summary: pytest plugin that checks URLs for HTML-containing files.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - blink1073
    - bollwyvl
